name: "ğŸ•µï¸"

on: [ push, pull_request ]

jobs:
  validation:
    name: "validate gradle wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
